version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            sbt docker

      - run:
          name: Run tests
          command: |
            docker run --rm default/sbt-docker-circleci2-example

